ATO-1254: Add information relating to max age
govuk-one-login/tech-docs pull request #304
Opened 2024-12-09 16:30 UTC by billrdunn

## Why

We will soon be supporting max age for some RPs. They will need to know how to include max age in their authorize request, and how to understand the auth_time claim in the response.

## What

Some additional 

## Technical writer support

- Should max age be included in the example requests? Bearing in mind that max age will not be available to all RPs.

## How to review

Check that my words are technically accurate and fit in the with the style of the documentation.

## Changelog

If this change is significant (for example, launching a new feature or deprecating a feature), you should update the changelog found at `partials/_changelog.erb`  under the heading 'Documentation updates'.

## Confirm

- [ ] I have checked if any docs change here also requires updates to other repositories (ADRs / RFCs, README.md, Team Manual, elsewhere in these docs)
- [ ] Where there is any overlap I have updated or opened a PR for corresponding changes

2024-12-17 10:03 UTC, ImogenCraigmile requested changes

2024-12-20 09:00 UTC, CarlyG55 commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +| `max_age`       | Optional             | Please note that max_age is by default not supported, and is only supported with prior approval. When the `max_age` parameter is included, your user will be
Is there a reason we want to link to GOV.UK? Seems a bit confusing for an RP to me?

2024-12-20 10:37 UTC, CarlyG55 commented
We probably want to update the changelog for this change

2024-12-23 14:44 UTC, CarlyG55 commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +1. If you included `max_age` in the request to the `/authorize` endpoint, you must validate that `auth_time` is greater than or equal to the current time subtract the value of `max_age`. If false, yo
This won't work - as far as I'm aware we only use prompt=login for reauth. You'll want them to reauth with max_age again

2024-12-27 10:50 UTC, ImogenCraigmile commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +| `max_age`       | Optional             | Please note that max_age is by default not supported, and is only supported with prior approval. When the `max_age` parameter is included, your user will be
That's a good point I think I was just popping in some kind of support link - would this be better https://home.account.gov.uk/contact-gov-uk-one-login? I was just trying to express that we know only one RP is using this parameter at this time but if other RPs want to could they contact someone?

2025-01-06 16:08 UTC, ImogenCraigmile commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +1. If you included `max_age` in the request to the `/authorize` endpoint, you must validate that `auth_time` is greater than or equal to the current time subtract the value of `max_age`. If false, yo
```suggestion
1. If you included `max_age` in the request to the `/authorize` endpoint, you must validate that `auth_time` is greater than or equal to the current time subtract the value of `max_age`. If false, you should reject the ID token and redirect the user to re-authenticate, by sending a new authroisation request including `max_age`.
```

2025-01-08 10:31 UTC, pauldougan commented
> We probably want to update the changelog for this change

+1 for adding it to the changelog, I was about to suggest this but you beat me to it!

2025-01-09 12:03 UTC, philf999 commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +| `max_age`       | Optional             | Please note that max_age is by default not supported, and is only supported with prior approval. When the `max_age` parameter is included, your user will be
I think it should be this link as it would be an RP contacting us - https://www.sign-in.service.gov.uk/support. It would be useful though if we could put the exceptions in the docs. If we don't we're going to get a lot of support questions.

2025-01-13 09:30 UTC, CarlyG55 commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +1. If you included `max_age` in the request to the `/authorize` endpoint, you must validate that `auth_time` is greater than or equal to the current time subtract the value of `max_age`. If false, yo
Think there's a typo here in `authorisation` 🙂

2025-01-13 10:04 UTC, ImogenCraigmile commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +| `max_age`       | Optional             | Please note that max_age is by default not supported, and is only supported with prior approval. When the `max_age` parameter is included, your user will be
Thanks both. I will rework this now.

2025-01-13 10:16 UTC, ImogenCraigmile commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +1. If you included `max_age` in the request to the `/authorize` endpoint, you must validate that `auth_time` is greater than or equal to the current time subtract the value of `max_age`. If false, yo
```suggestion
1. If you included `max_age` in the request to the `/authorize` endpoint, you must validate that `auth_time` is greater than or equal to the current time subtract the value of `max_age`. If false, you should reject the ID token and redirect the user to re-authenticate, by sending a new authorisation request including `max_age`.
```

2025-01-13 10:31 UTC, ImogenCraigmile commented on source/partials/_changelog.erb
> +| Jan 13 2025      | Updates guidance <a href="/integrate-with-integration-environment/authenticate-your-user.html.md.erb">"Authenticate your user"</a> to add information about configuring max_age pa
```suggestion
| Jan 13 2025      | Updates guidance <a href="/integrate-with-integration-environment/authenticate-your-user">"Authenticate your user"</a> to add information about configuring max_age parameter.                                                                 |
```

2025-01-13 10:37 UTC, CarlyG55 commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +| `max_age`       | Optional             | `max_age` is only available to services not on the GOV.UK domain and those handling particularly sensitive data. Contact GOV.UK One Login support (https://w
```suggestion
| `max_age`       | Optional             | `max_age` is only available to services not on the GOV.UK domain and those handling particularly sensitive data. Contact GOV.UK One Login support (https://www.sign-in.service.gov.uk/support) for more information. When the `max_age` parameter is included in your request, your user will be forced to reauthenticate if the time in seconds since authentication is greater than `max_age`. `max_age` must be set to zero or a positive integer. |
```
Not sure this will work with the full stop 🙂

2025-01-13 10:41 UTC, ImogenCraigmile commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +| `max_age`       | Optional             | `max_age` is only available to services not on the GOV.UK domain and those handling particularly sensitive data. Contact GOV.UK One Login support (https://w
Good point! Thanks

2025-01-13 10:49 UTC, CarlyG55 approved these changes

2025-01-20 08:30 UTC, pauldougan commented on source/partials/_changelog.erb
> +| Jan 13 2025      | Updates guidance <a href="/integrate-with-integration-environment/authenticate-your-user">"Authenticate your user"</a> to add information about configuring max_age parameter.
suggest replace "configuring max_age parameter." with "configuring the `max_age` parameter

2025-01-20 08:46 UTC, ImogenCraigmile commented on source/partials/_changelog.erb
> +| Jan 13 2025      | Updates guidance <a href="/integrate-with-integration-environment/authenticate-your-user">"Authenticate your user"</a> to add information about configuring max_age parameter.
```suggestion
| Jan 13 2025      | Updates guidance <a href="/integrate-with-integration-environment/authenticate-your-user">"Authenticate your user"</a> to add information about configuring the max_age parameter.                                                                 |
```

2025-01-21 08:41 UTC, PippaClarkGDS reviewed
Left some comments, can take another look when these are resolved

2025-01-21 08:41 UTC, PippaClarkGDS commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +| `max_age`       | Optional             | `max_age` is only available to services not on the GOV.UK domain and those handling particularly sensitive data. Contact GOV.UK One Login support (https://w
```suggestion
| `max_age`       | Optional             | `max_age` is only available to services not on the GOV.UK domain and those handling particularly sensitive data. [Contact GOV.UK One Login support](https://www.sign-in.service.gov.uk/support) for more information. If you include the `max_age` parameter in your request, your user will be forced to re-authenticate if the time in seconds since authentication (shown as `auth_time` in the `/authorize` response) is greater than `max_age`. `max_age` must be set to zero or a positive integer. |
```

2025-01-21 08:41 UTC, PippaClarkGDS commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +| `max_age`       | Optional             | `max_age` is only available to services not on the GOV.UK domain and those handling particularly sensitive data. Contact GOV.UK One Login support (https://w
Would recommend we give examples of what sensitive information might necessitate including max_age to stop too many services contacting us to find out. Which ones could work?

2025-01-21 08:41 UTC, PippaClarkGDS commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +| `max_age`       | Optional             | `max_age` is only available to services not on the GOV.UK domain and those handling particularly sensitive data. Contact GOV.UK One Login support (https://w
have included an assumption about auth_time. Might be worth getting SME to check this

2025-01-21 08:41 UTC, PippaClarkGDS commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +| `auth_time` | `auth_time` is the time at which your user last authenticated, which will be an integer timestamp representing the number of seconds since the [Unix Epoch][external.unix-epoch]. |
```suggestion
| `auth_time` | `auth_time` is the time at which your user last authenticated. This will be an integer timestamp representing the number of seconds since the [Unix Epoch][external.unix-epoch]. |
```

2025-01-21 08:41 UTC, PippaClarkGDS commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +1. If you included `max_age` in the request to the `/authorize` endpoint, you must validate that `auth_time` is greater than or equal to the current time subtract the value of `max_age`. If false, yo
```suggestion
1. If you included `max_age` in the request to the `/authorize` endpoint, you must validate `auth_time`. `auth_time` must be greater than or equal to the current time after subtracting the value of `max_age`. If false, you should reject the ID token and redirect the user to re-authenticate, by sending a new authorisation request including `max_age`.
```

2025-01-21 08:41 UTC, PippaClarkGDS commented on source/partials/_changelog.erb
> +| Jan 13 2025      | Updates guidance <a href="/integrate-with-integration-environment/authenticate-your-user">"Authenticate your user"</a> to add information about configuring the max_age parameter.
```suggestion
| Jan 13 2025      | Updates guidance <a href="/integrate-with-integration-environment/authenticate-your-user">"Authenticate your user"</a> to add information about using the `max_age` parameter.                                                             |
```

2025-01-21 08:41 UTC, PippaClarkGDS commented on source/partials/_changelog.erb
> +| Jan 13 2025      | Updates guidance <a href="/integrate-with-integration-environment/authenticate-your-user">"Authenticate your user"</a> to add information about configuring the max_age parameter.
would recommend you include a second sentence following this first one to say ......"to add information about validating the `max_age` parameter."

2025-01-23 14:19 UTC, CarlyG55 commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +| `max_age`       | Optional             | `max_age` is only available to services not on the GOV.UK domain and those handling particularly sensitive data. Contact GOV.UK One Login support (https://w
@philf999 re the sensitive information, I think this is one for you

2025-01-23 14:27 UTC, CarlyG55 commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +| `max_age`       | Optional             | `max_age` is only available to services not on the GOV.UK domain and those handling particularly sensitive data. Contact GOV.UK One Login support (https://w
I think the update you've added makes it a bit harder to read for me. `max_age` is the number of seconds since the last authentication that RP's are happy to accept - often zero. `auth_time` is a timestamp, represented in seconds - the current time represented that way is about `1737642273`.  When the RP makes the request, unless it's the second request in a row, they likely won't know what the `auth_time` is, as that's returned in the id_token, not the authorise response, and they don't get this until after they've authenticated

2025-01-23 15:03 UTC, philf999 submitted a review, later dismissed
Left a few comments but happy to approve

2025-01-23 15:03 UTC, philf999 commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +| `auth_time` | `auth_time` is the time at which your user last authenticated, which will be an integer timestamp representing the number of seconds since the [Unix Epoch][external.unix-epoch]. |
```suggestion
| `auth_time` | `auth_time` is the time user authentication occurred, an integer timestamp representing the number of seconds since the [Unix Epoch][external.unix-epoch]. |
```

2025-01-23 15:03 UTC, philf999 commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +1. If you included `max_age` in the request to the `/authorize` endpoint, you must validate that `auth_time` is greater than or equal to the current time subtract the value of `max_age`. If false, yo
Do we need to allow for differences in the time on the OL server and the RP? If the time between issuing a token and validation is over 1 second this would fail

2025-01-24 09:47 UTC, CarlyG55 commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +1. If you included `max_age` in the request to the `/authorize` endpoint, you must validate that `auth_time` is greater than or equal to the current time subtract the value of `max_age`. If false, yo
Do we ask RPs to take this into account anywhere else?

2025-01-24 10:34 UTC, philf999 commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +1. If you included `max_age` in the request to the `/authorize` endpoint, you must validate that `auth_time` is greater than or equal to the current time subtract the value of `max_age`. If false, yo
I don't think so. But this is the only place that a a very small time difference or just the response time could be enough for validation to fail.

The instruction in the Open ID spec side step this by using this wording:

If the auth_time ... by using the max_age parameter, the Client SHOULD check the auth_time Claim value and request re-authentication (again) if it determines too much time has elapsed since the last End-User authentication.

2025-01-24 16:29 UTC, PippaClarkGDS commented on source/integrate-with-integration-environment/authenticate-your-user.html.md.erb
> +| `max_age`       | Optional             | `max_age` is only available to services not on the GOV.UK domain and those handling particularly sensitive data. Contact GOV.UK One Login support (https://w
Happy to keep to the original if adding auth_time might be confusing to users. 

Re sensitive information, my hunch is that if we keep it vague, the RP uptake might be slow as they might not realise they do/do not want to use it. One to keep an eye on and see if it's getting the adoption we're expecting

2025-01-27 09:40 UTC, ImogenCraigmile approved these changes

2025-01-27 11:05 UTC, merged